apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: fake-app-test-analysis
spec:
  metrics:
  - name: fake-app-test
    count: 1
    interval: 0s
    failureLimit: 0
    provider:
      job:
        spec:
          backoffLimit: 0 # run once
          ttlSecondsAfterFinished: 1800
          template:
            spec:
              containers:
              - name: fake-app-test
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                command: ["./test.sh"]
                env:
                  - name: HOST
                    value: "fake-app-preview"
                  - name: PORT
                    value: "80"
                  - name: MARKER
                    value: "passing"
              restartPolicy: Never