---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fake-app.fullname" . }}
  labels:
    app: {{ template "fake-app.name" . }}
    chart: {{ template "fake-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "fake-app.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fake-app.fullname" . }}-preview
  labels:
    app: {{ template "fake-app.name" . }}
    chart: {{ template "fake-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "fake-app.name" . }}
    release: {{ .Release.Name }}
